sudo: false
language: c
os:
  # osx starts faster because homebrew installs beat building from source
#  - osx
  - linux
compiler:
#  - clang
  - gcc
env:
  - MPI_IMPL=mpich SMP_OPT=0
  - MPI_IMPL=mpich SMP_OPT=1
  - MPI_IMPL=openmpi SMP_OPT=0
  - MPI_IMPL=openmpi SMP_OPT=1
matrix:
  allow_failures:
    - env: MPI_IMPL=openmpi SMP_OPT=0
      os: osx
    - env: MPI_IMPL=openmpi SMP_OPT=1
      os: osx
    - env: MPI_IMPL=openmpi SMP_OPT=0
      os: linux
    - env: MPI_IMPL=openmpi SMP_OPT=1
      os: linux
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - sh ./travis/install-autotools.sh $TRAVIS_ROOT
install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL
script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL $SMP_OPT
after_failure:
  - cat ./config.log
  - cat ./test-suite.log
  - find . -name "*.log" -exec head -n 100 {} ";"
