sudo: true
language: c
os:
  - linux
  #- osx
compiler:
  - gcc
  #- clang
env:
  - MPI_IMPL=mpich SMP_OPT=0
  - MPI_IMPL=mpich SMP_OPT=1
  #- MPI_IMPL=openmpi
before_install:
  - sh ./travis/install-deps.sh $MPI_IMPL
script:
  - sh ./travis/build-run.sh $SMP_OPT
after_failure:
  - cat ./config.log
  - head -n100 ./tests/*.log
